# Generated by Django 5.2.7 on 2025-10-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_app', '0002_skillad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillad',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='skillad',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
